.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. alaris_qt test_alaris_qt
clean: FORCE
	$(MAKE) -C .. alaris_qt_clean test_alaris_qt_clean
check: FORCE
	$(MAKE) -C .. test_alaris_qt_check
alaris-qt alaris-qt.exe: FORCE
	 $(MAKE) -C .. alaris_qt
